services:
  my-server:
    build: .
    ports:
      - 8080:8080
    depends_on: #my-server will run when condition is fulfilled
      my-db:
        condition: service_healthy #my-server will run when my-db service_healthy
  my-db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: MoimSQL02!
      MYSQL_DATABASE: moim
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    healthcheck: #how to do health_check for my-db
      test: ["CMD", "mysqladmin", "ping"]
      interval: 5s
      retries: 10