name: CD

# event: 실행되는 시점을 설정
on:
  push:
    branches:
      - develop

jobs:
  deploy:
    # 내 github actions를 실행할 컴퓨터 OS
    runs-on: ubuntu-latest

    steps:
      - name: connect EC2 through SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{secrets.EC2_PRIVATE_KEY }} #EC2만들 때 다운받은 pem키
          script: | 
            cd /home/ec2-user/Moim-BE
            git pull origin main
            ./gradlew clean build -x test
            sudo fuser -k -n tcp 8080 || true
            nohup java -jar build/libs/*SNAPSHOT.jar > ./output.log  2>&1 & 

